### ISSUE TITLE
OFFSET

### ISSUE THREAD

**Issue by ct1esj** [ManoDaSilva/ESP32-Pocsag-Pager#4]
Good afternoon. The project is very good. Now a question: Where do I put the offset value in the structure, it says in RIC, but I'm not really understanding where. I can't receive anything, the Lora isn't listening to the mmdvm, it's out of frequency. Another question, is it really necessary to join pins DIO1 and 2 with pins 34 and 35? Can you identify the pins? Thank you, I'll follow the evolution of the project because I really liked it. Best regards CT1ESJ - Henrique

**Comment by ManoDaSilva** [comment]
Olá! Sorry about the delay! 

The offset is to be set in config.h (in src/ dir). I'm currently implementing a "test Tx" feature to make things easier and measure the offset with an RTL-SDR or anything else :) 

As for the DIO pins, yes, you need to bridge them as you need a "direct input" for 2FSK decoding. They're labeled LORA1 and LORA2 on most boards. Again, I'll clarify this on the README.md file. 

Comprimentos,
Manoel
